version: "3.7"

volumes:
  godictvolume:
    name: godict-volume

networks:
  godictnetwork:
    name: godict-network

services:
#  pg:
#    image: postgres:12.0
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    volumes:
#      - boilerplatevolume:/var/lib/postgresql/data
#      - ./db/jenkins-guide:/docker-entrypoint-initdb.d/
#    networks:
#      - boilerplatenetwork
  godict_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    depends_on:
#      - pg
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - godictnetwork
#    env_file:
#      - .env
    entrypoint: ["/bin/bash", "./run.sh"]