version: "3.7"

volumes:
  goDictvolume:
    name: goDict-volume

networks:
  goDictnetwork:
    name: goDict-network

services:
#  pg:
#    image: postgres:12.0
#    restart: on-failure
#    env_file:
#      - .env
#    ports:
#      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
#    volumes:
#      - boilerplatevolume:/var/lib/postgresql/data
#      - ./db/scripts:/docker-entrypoint-initdb.d/
#    networks:
#      - boilerplatenetwork
  goDict_api:
    build:
      context: .
      dockerfile: Dockerfile.dev
#    depends_on:
#      - pg
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    networks:
      - goDictnetwork
#    env_file:
#      - .env
    entrypoint: ["/bin/bash", "./scripts/entrypoint.dev.sh"]